create table if not exists public.students (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    course varchar(100) not null,
    marks integer not null check (marks >= 0 and marks <= 100)
);
